### ISSUE TITLE
Cannot install, getting this error

### ISSUE THREAD

**Issue by developernaren** [driftphp/mysql-bundle#4]
I am getting this error when trying to install in driftphp.

```
Problem 1
    - The requested package drift/http-kernel (installed at 0.1.5, required as 0.1.*, >=0.1.7) is satisfiable by drift/http-kernel[0.1.5] but these conflict with your requirements or minimum-stability.
  Problem 2
    - The requested package drift/server (installed at 0.1.4, required as 0.1.*, >=0.1.7) is satisfiable by drift/server[0.1.4] but these conflict with your requirements or minimum-stability.
```

I have tried to set this in `composer.json`

```json
"minimum-stability": "dev",
 "prefer-stable": true
```
but not working.
I am using `PHP 7.3.6`.

**Comment by mmoreram** [comment]
The demo?

**Comment by mmoreram** [comment]
Make sure all your DriftPHP components are installed by using the `0.1.*` version. None of them are required in `dev` anymore.

**Comment by developernaren** [comment]
```
"drift/http-kernel": "^0.1.9",
"drift/server": "^0.1.7",
```
changed the versions to these and it worked.
I was using the skeleton.
thanks for the quick reply.

**Comment by mmoreram** [comment]
@developernaren I don't understand why the old configuration was failing. I've tried the regular skeleton `composer.json` and should work. Can you paste here your old composer file?

Thanks :D

**Comment by developernaren** [comment]
@mmoreram I just did this 
`composer create-project drift/skeleton -sdev`
It was a fresh installation from the doc.

**Comment by mmoreram** [comment]
@developernaren I can do this, and everything works as expected :S Weird...

**Comment by developernaren** [comment]
The project is working fine.  @mmoreram I just cannot add the ``mysql-bundle` or `postgres` even. It worked after I removed from composer.json and manually installed install `server` and `http-kernel`.  Anyway, it's working for me now.
BTW great work on driftphp. Makes getting into non-blocking PHP easy. I am playing with this. And feels good writing promises in PHP :)

**Comment by mmoreram** [comment]
@developernaren Okay! I'll take a look then :D

Thanks so much for your words.
Please, let me know if you have any problems sometimes with the project -> https://gitter.im/driftphp/community

:)
